version: "3.8"

services:
  backend:
    build: .
    container_name: meditation-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
